name: Cron Worker - run monitor checks

# Run every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  run-cron-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: uptime-backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run cron worker (process due monitors)
        env:
          DATABASE_URL: ${{ postgresql://uptime_db_x5yw_user:6cTLmQN4fafezR1kWAr6QEpaR8M65TXC@dpg-d4i2kji4d50c73cm9bm0-a/uptime_db_x5yw }}
          REDIS_URL: ${{ redis://default:AV20AAIncDI2OTRkYzM1MTczNWM0OWJjYTQ4YjEzMjQ2MDA5ODYwNHAyMjM5ODg@enabling-jackal-23988.upstash.io:6379 }}
          WHATSAPP_API_KEY: ${{ secrets.WHATSAPP_API_KEY }}
          SENDGRID_API_KEY: ${{ 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 }}
          ALERT_FROM_EMAIL: ${{ rjkumar081@gmail.com }}
        run: |
          echo "Starting cron worker"
          node worker/cronWorker.js
